name: Run Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        php: ['8.2', '8.3']

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer, phpunit, pest
          coverage: none

      - name: Install Dependencies
        run: composer install --prefer-dist --no-progress

      - name: Make Pint executable
        run: chmod +x ./vendor/bin/pint

      - name: Make Rector executable
        run: chmod +x ./vendor/bin/rector

      - name: Run Pint
        run: ./vendor/bin/pint --test

      - name: Run Rector (dry run)
        run: ./vendor/bin/rector process --dry-run

      - name: Run PHPUnit Tests
        run: ./vendor/bin/phpunit

      - name: Run Pest Tests
        run: ./vendor/bin/pest
